# Generated by Django 3.2.9 on 2021-11-01 16:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('studio', models.CharField(max_length=50)),
                ('release_published', models.DateTimeField(blank=True, default=datetime.date.today)),
                ('genre', models.CharField(choices=[('FPS', 'first-person shooter'), ('RP', 'role playing'), ('P', 'puzzle'), ('AG', 'action game')], max_length=3)),
                ('fsk', models.CharField(choices=[('0', 'von 0'), ('6', 'ab 6 Jahre'), ('12', 'ab 12 Jahre'), ('16', 'ab 16 Jahre'), ('18', 'ab 18 Jahre')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['name', '-genre'],
            },
        ),
    ]
