# Generated by Django 3.2.9 on 2021-11-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_published',
            field=models.DateTimeField(),
        ),
    ]
